/*
 * Fideo API
 * Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@fideo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.fideo.api;

import ai.fideo.client.ApiException;
import ai.fideo.model.SignalPatternRecencyResponse;
import ai.fideo.model.SignalPatternResponseUnit;
import ai.fideo.model.SignalPatternsRequest;
import ai.fideo.model.SignalPatternsTimeseriesRequest;
import ai.fideo.model.StatusResponseWithMessage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BetaApi
 */
@Disabled
public class BetaApiTest {

    private final BetaApi api = new BetaApi();

    /**
     * Get signal patterns summary
     *
     * Returns summaries of ALL intervals (hour through year) for an email in the request
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSignalPatternsSummaryTest() throws ApiException {
        SignalPatternsRequest signalPatternsRequest = null;
        SignalPatternRecencyResponse response = api.getSignalPatternsSummary(signalPatternsRequest);
        // TODO: test validations
    }

    /**
     * Get signal patterns timeseries
     *
     * Returns timeseries details for signal patterns
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSignalPatternsTimeseriesTest() throws ApiException {
        SignalPatternsTimeseriesRequest signalPatternsTimeseriesRequest = null;
        Map<String, SignalPatternResponseUnit> response = api.getSignalPatternsTimeseries(signalPatternsTimeseriesRequest);
        // TODO: test validations
    }

}
