/*
 * Fideo API
 * Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@fideo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.fideo.api;

import ai.fideo.client.ApiException;
import ai.fideo.model.MultiFieldReqWithOptions;
import ai.fideo.model.PrefillResponse;
import ai.fideo.model.StatusResponseWithMessage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PrefillApi
 */
@Disabled
public class PrefillApiTest {

    private final PrefillApi api = new PrefillApi();

    /**
     * Resolve or evaluate onboarding identity fields
     *
     * The customer is responsible for proving phone possession before the initial request. Omit sessionId to resolve identity fields from a phone. Send the returned sessionId with reviewed or edited identity fields to receive a Verify evaluation. Recent session IDs are reused; valid session IDs older than 10 minutes start a new session.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void prefillTest() throws ApiException {
        MultiFieldReqWithOptions multiFieldReqWithOptions = null;
        PrefillResponse response = api.prefill(multiFieldReqWithOptions);
        // TODO: test validations
    }

}
