/*
 * Fideo API
 * Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@fideo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.fideo.api;

import ai.fideo.client.ApiException;
import ai.fideo.model.MultiFieldReq;
import ai.fideo.model.VerifyResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VerifyApi
 */
@Disabled
public class VerifyApiTest {

    private final VerifyApi api = new VerifyApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyPostTest() throws ApiException {
        MultiFieldReq multiFieldReq = null;
        VerifyResponse response = api.verifyPost(multiFieldReq);
        // TODO: test validations
    }

}
