/*
 * Fideo API
 * This is a representation of the Fideo API based on the OpenAPI 3.0 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). Some useful links: - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@fideo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.fideo.api;

import ai.fideo.client.ApiException;
import ai.fideo.model.MatchResponse;
import ai.fideo.model.MultiFieldReq;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VerifyApi
 */
@Disabled
public class VerifyApiTest {

    private final VerifyApi api = new VerifyApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyMatchPostTest() throws ApiException {
        MultiFieldReq multiFieldReq = null;
        MatchResponse response = api.verifyMatchPost(multiFieldReq);
        // TODO: test validations
    }

}
