/*
 * Fideo API
 * Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@fideo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.fideo.api;

import ai.fideo.client.ApiCallback;
import ai.fideo.client.ApiClient;
import ai.fideo.client.ApiException;
import ai.fideo.client.ApiResponse;
import ai.fideo.client.Configuration;
import ai.fideo.client.Pair;
import ai.fideo.client.ProgressRequestBody;
import ai.fideo.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.fideo.model.SignalPatternRecencyResponse;
import ai.fideo.model.SignalPatternResponseUnit;
import ai.fideo.model.SignalPatternsRequest;
import ai.fideo.model.SignalPatternsTimeseriesRequest;
import ai.fideo.model.StatusResponseWithMessage;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BetaApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public BetaApi() {
        this(Configuration.getDefaultApiClient());
    }

    public BetaApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getSignalPatternsSummary
     * @param signalPatternsRequest  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getSignalPatternsSummaryCall(@javax.annotation.Nullable SignalPatternsRequest signalPatternsRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = signalPatternsRequest;

        // create path and map variables
        String localVarPath = "/beta/signals/patterns/summary";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getSignalPatternsSummaryValidateBeforeCall(@javax.annotation.Nullable SignalPatternsRequest signalPatternsRequest, final ApiCallback _callback) throws ApiException {
        return getSignalPatternsSummaryCall(signalPatternsRequest, _callback);

    }

    /**
     * Get signal patterns summary
     * Returns summaries of ALL intervals (hour through year) for an email in the request
     * @param signalPatternsRequest  (optional)
     * @return SignalPatternRecencyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
     </table>
     */
    public SignalPatternRecencyResponse getSignalPatternsSummary(@javax.annotation.Nullable SignalPatternsRequest signalPatternsRequest) throws ApiException {
        ApiResponse<SignalPatternRecencyResponse> localVarResp = getSignalPatternsSummaryWithHttpInfo(signalPatternsRequest);
        return localVarResp.getData();
    }

    /**
     * Get signal patterns summary
     * Returns summaries of ALL intervals (hour through year) for an email in the request
     * @param signalPatternsRequest  (optional)
     * @return ApiResponse&lt;SignalPatternRecencyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SignalPatternRecencyResponse> getSignalPatternsSummaryWithHttpInfo(@javax.annotation.Nullable SignalPatternsRequest signalPatternsRequest) throws ApiException {
        okhttp3.Call localVarCall = getSignalPatternsSummaryValidateBeforeCall(signalPatternsRequest, null);
        Type localVarReturnType = new TypeToken<SignalPatternRecencyResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get signal patterns summary (asynchronously)
     * Returns summaries of ALL intervals (hour through year) for an email in the request
     * @param signalPatternsRequest  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getSignalPatternsSummaryAsync(@javax.annotation.Nullable SignalPatternsRequest signalPatternsRequest, final ApiCallback<SignalPatternRecencyResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getSignalPatternsSummaryValidateBeforeCall(signalPatternsRequest, _callback);
        Type localVarReturnType = new TypeToken<SignalPatternRecencyResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getSignalPatternsTimeseries
     * @param signalPatternsTimeseriesRequest  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getSignalPatternsTimeseriesCall(@javax.annotation.Nullable SignalPatternsTimeseriesRequest signalPatternsTimeseriesRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = signalPatternsTimeseriesRequest;

        // create path and map variables
        String localVarPath = "/beta/signals/patterns/timeseries";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getSignalPatternsTimeseriesValidateBeforeCall(@javax.annotation.Nullable SignalPatternsTimeseriesRequest signalPatternsTimeseriesRequest, final ApiCallback _callback) throws ApiException {
        return getSignalPatternsTimeseriesCall(signalPatternsTimeseriesRequest, _callback);

    }

    /**
     * Get signal patterns timeseries
     * Returns timeseries details for signal patterns
     * @param signalPatternsTimeseriesRequest  (optional)
     * @return Map&lt;String, SignalPatternResponseUnit&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
     </table>
     */
    public Map<String, SignalPatternResponseUnit> getSignalPatternsTimeseries(@javax.annotation.Nullable SignalPatternsTimeseriesRequest signalPatternsTimeseriesRequest) throws ApiException {
        ApiResponse<Map<String, SignalPatternResponseUnit>> localVarResp = getSignalPatternsTimeseriesWithHttpInfo(signalPatternsTimeseriesRequest);
        return localVarResp.getData();
    }

    /**
     * Get signal patterns timeseries
     * Returns timeseries details for signal patterns
     * @param signalPatternsTimeseriesRequest  (optional)
     * @return ApiResponse&lt;Map&lt;String, SignalPatternResponseUnit&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Map<String, SignalPatternResponseUnit>> getSignalPatternsTimeseriesWithHttpInfo(@javax.annotation.Nullable SignalPatternsTimeseriesRequest signalPatternsTimeseriesRequest) throws ApiException {
        okhttp3.Call localVarCall = getSignalPatternsTimeseriesValidateBeforeCall(signalPatternsTimeseriesRequest, null);
        Type localVarReturnType = new TypeToken<Map<String, SignalPatternResponseUnit>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get signal patterns timeseries (asynchronously)
     * Returns timeseries details for signal patterns
     * @param signalPatternsTimeseriesRequest  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getSignalPatternsTimeseriesAsync(@javax.annotation.Nullable SignalPatternsTimeseriesRequest signalPatternsTimeseriesRequest, final ApiCallback<Map<String, SignalPatternResponseUnit>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getSignalPatternsTimeseriesValidateBeforeCall(signalPatternsTimeseriesRequest, _callback);
        Type localVarReturnType = new TypeToken<Map<String, SignalPatternResponseUnit>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
