/*
 * Fideo API
 * Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@fideo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.fideo.api;

import ai.fideo.client.ApiCallback;
import ai.fideo.client.ApiClient;
import ai.fideo.client.ApiException;
import ai.fideo.client.ApiResponse;
import ai.fideo.client.Configuration;
import ai.fideo.client.Pair;
import ai.fideo.client.ProgressRequestBody;
import ai.fideo.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.fideo.model.LensGraphRequest;
import ai.fideo.model.LensGraphResponse;
import ai.fideo.model.StatusResponseWithMessage;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LensApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public LensApi() {
        this(Configuration.getDefaultApiClient());
    }

    public LensApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for lensGraph
     * @param lensGraphRequest  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  * X-Fideo-Limit -  <br>  * X-Fideo-Usage -  <br>  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Lens usage limit reached </td><td>  * X-Fideo-Limit -  <br>  * X-Fideo-Usage -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call lensGraphCall(@javax.annotation.Nullable LensGraphRequest lensGraphRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = lensGraphRequest;

        // create path and map variables
        String localVarPath = "/lens.graph";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call lensGraphValidateBeforeCall(@javax.annotation.Nullable LensGraphRequest lensGraphRequest, final ApiCallback _callback) throws ApiException {
        return lensGraphCall(lensGraphRequest, _callback);

    }

    /**
     * Query the Lens graph
     * Query raw or expanded Lens graph edges. Product and datapack entitlements are derived from the account contract, not from the request body.
     * @param lensGraphRequest  (optional)
     * @return LensGraphResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  * X-Fideo-Limit -  <br>  * X-Fideo-Usage -  <br>  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Lens usage limit reached </td><td>  * X-Fideo-Limit -  <br>  * X-Fideo-Usage -  <br>  </td></tr>
     </table>
     */
    public LensGraphResponse lensGraph(@javax.annotation.Nullable LensGraphRequest lensGraphRequest) throws ApiException {
        ApiResponse<LensGraphResponse> localVarResp = lensGraphWithHttpInfo(lensGraphRequest);
        return localVarResp.getData();
    }

    /**
     * Query the Lens graph
     * Query raw or expanded Lens graph edges. Product and datapack entitlements are derived from the account contract, not from the request body.
     * @param lensGraphRequest  (optional)
     * @return ApiResponse&lt;LensGraphResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  * X-Fideo-Limit -  <br>  * X-Fideo-Usage -  <br>  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Lens usage limit reached </td><td>  * X-Fideo-Limit -  <br>  * X-Fideo-Usage -  <br>  </td></tr>
     </table>
     */
    public ApiResponse<LensGraphResponse> lensGraphWithHttpInfo(@javax.annotation.Nullable LensGraphRequest lensGraphRequest) throws ApiException {
        okhttp3.Call localVarCall = lensGraphValidateBeforeCall(lensGraphRequest, null);
        Type localVarReturnType = new TypeToken<LensGraphResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Query the Lens graph (asynchronously)
     * Query raw or expanded Lens graph edges. Product and datapack entitlements are derived from the account contract, not from the request body.
     * @param lensGraphRequest  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  * X-Fideo-Limit -  <br>  * X-Fideo-Usage -  <br>  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Lens usage limit reached </td><td>  * X-Fideo-Limit -  <br>  * X-Fideo-Usage -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call lensGraphAsync(@javax.annotation.Nullable LensGraphRequest lensGraphRequest, final ApiCallback<LensGraphResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = lensGraphValidateBeforeCall(lensGraphRequest, _callback);
        Type localVarReturnType = new TypeToken<LensGraphResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
