/*
 * Fideo API
 * Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@fideo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.fideo.api;

import ai.fideo.client.ApiCallback;
import ai.fideo.client.ApiClient;
import ai.fideo.client.ApiException;
import ai.fideo.client.ApiResponse;
import ai.fideo.client.Configuration;
import ai.fideo.client.Pair;
import ai.fideo.client.ProgressRequestBody;
import ai.fideo.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.fideo.model.MultiFieldReqWithOptions;
import ai.fideo.model.PrefillResponse;
import ai.fideo.model.StatusResponseWithMessage;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PrefillApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public PrefillApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PrefillApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for prefill
     * @param multiFieldReqWithOptions  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Prefill match, no-match, or reviewed identity evaluation </td><td>  * X-Fideo-Limit -  <br>  * X-Fideo-Usage -  <br>  </td></tr>
        <tr><td> 400 </td><td> Invalid request or malformed Prefill session ID </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Prefill product unavailable </td><td>  -  </td></tr>
        <tr><td> 410 </td><td> Claimed or deleted data </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Prefill trial request limit reached </td><td>  * X-Fideo-Limit -  <br>  * X-Fideo-Usage -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call prefillCall(@javax.annotation.Nonnull MultiFieldReqWithOptions multiFieldReqWithOptions, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = multiFieldReqWithOptions;

        // create path and map variables
        String localVarPath = "/prefill";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call prefillValidateBeforeCall(@javax.annotation.Nonnull MultiFieldReqWithOptions multiFieldReqWithOptions, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'multiFieldReqWithOptions' is set
        if (multiFieldReqWithOptions == null) {
            throw new ApiException("Missing the required parameter 'multiFieldReqWithOptions' when calling prefill(Async)");
        }

        return prefillCall(multiFieldReqWithOptions, _callback);

    }

    /**
     * Resolve or evaluate onboarding identity fields
     * The customer is responsible for proving phone possession before the initial request. Omit sessionId to resolve identity fields from a phone. Send the returned sessionId with reviewed or edited identity fields to receive a Verify evaluation. Recent session IDs are reused; valid session IDs older than 10 minutes start a new session.
     * @param multiFieldReqWithOptions  (required)
     * @return PrefillResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Prefill match, no-match, or reviewed identity evaluation </td><td>  * X-Fideo-Limit -  <br>  * X-Fideo-Usage -  <br>  </td></tr>
        <tr><td> 400 </td><td> Invalid request or malformed Prefill session ID </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Prefill product unavailable </td><td>  -  </td></tr>
        <tr><td> 410 </td><td> Claimed or deleted data </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Prefill trial request limit reached </td><td>  * X-Fideo-Limit -  <br>  * X-Fideo-Usage -  <br>  </td></tr>
     </table>
     */
    public PrefillResponse prefill(@javax.annotation.Nonnull MultiFieldReqWithOptions multiFieldReqWithOptions) throws ApiException {
        ApiResponse<PrefillResponse> localVarResp = prefillWithHttpInfo(multiFieldReqWithOptions);
        return localVarResp.getData();
    }

    /**
     * Resolve or evaluate onboarding identity fields
     * The customer is responsible for proving phone possession before the initial request. Omit sessionId to resolve identity fields from a phone. Send the returned sessionId with reviewed or edited identity fields to receive a Verify evaluation. Recent session IDs are reused; valid session IDs older than 10 minutes start a new session.
     * @param multiFieldReqWithOptions  (required)
     * @return ApiResponse&lt;PrefillResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Prefill match, no-match, or reviewed identity evaluation </td><td>  * X-Fideo-Limit -  <br>  * X-Fideo-Usage -  <br>  </td></tr>
        <tr><td> 400 </td><td> Invalid request or malformed Prefill session ID </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Prefill product unavailable </td><td>  -  </td></tr>
        <tr><td> 410 </td><td> Claimed or deleted data </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Prefill trial request limit reached </td><td>  * X-Fideo-Limit -  <br>  * X-Fideo-Usage -  <br>  </td></tr>
     </table>
     */
    public ApiResponse<PrefillResponse> prefillWithHttpInfo(@javax.annotation.Nonnull MultiFieldReqWithOptions multiFieldReqWithOptions) throws ApiException {
        okhttp3.Call localVarCall = prefillValidateBeforeCall(multiFieldReqWithOptions, null);
        Type localVarReturnType = new TypeToken<PrefillResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Resolve or evaluate onboarding identity fields (asynchronously)
     * The customer is responsible for proving phone possession before the initial request. Omit sessionId to resolve identity fields from a phone. Send the returned sessionId with reviewed or edited identity fields to receive a Verify evaluation. Recent session IDs are reused; valid session IDs older than 10 minutes start a new session.
     * @param multiFieldReqWithOptions  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Prefill match, no-match, or reviewed identity evaluation </td><td>  * X-Fideo-Limit -  <br>  * X-Fideo-Usage -  <br>  </td></tr>
        <tr><td> 400 </td><td> Invalid request or malformed Prefill session ID </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Prefill product unavailable </td><td>  -  </td></tr>
        <tr><td> 410 </td><td> Claimed or deleted data </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Prefill trial request limit reached </td><td>  * X-Fideo-Limit -  <br>  * X-Fideo-Usage -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call prefillAsync(@javax.annotation.Nonnull MultiFieldReqWithOptions multiFieldReqWithOptions, final ApiCallback<PrefillResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = prefillValidateBeforeCall(multiFieldReqWithOptions, _callback);
        Type localVarReturnType = new TypeToken<PrefillResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
