/*
 * Fideo API
 * Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@fideo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.fideo.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.fideo.client.JSON;

/**
 * LensGraphResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class LensGraphResponse {
  public static final String SERIALIZED_NAME_GRAPH = "graph";
  @SerializedName(SERIALIZED_NAME_GRAPH)
  @javax.annotation.Nullable
  private List<Object> graph = new ArrayList<>();

  public static final String SERIALIZED_NAME_SEED_GRAPH_IDS = "seed_graph_ids";
  @SerializedName(SERIALIZED_NAME_SEED_GRAPH_IDS)
  @javax.annotation.Nullable
  private Map<String, List<String>> seedGraphIds = new HashMap<>();

  public LensGraphResponse() {
  }

  public LensGraphResponse graph(@javax.annotation.Nullable List<Object> graph) {
    this.graph = graph;
    return this;
  }

  public LensGraphResponse addGraphItem(Object graphItem) {
    if (this.graph == null) {
      this.graph = new ArrayList<>();
    }
    this.graph.add(graphItem);
    return this;
  }

  /**
   * Get graph
   * @return graph
   */
  @javax.annotation.Nullable
  public List<Object> getGraph() {
    return graph;
  }

  public void setGraph(@javax.annotation.Nullable List<Object> graph) {
    this.graph = graph;
  }


  public LensGraphResponse seedGraphIds(@javax.annotation.Nullable Map<String, List<String>> seedGraphIds) {
    this.seedGraphIds = seedGraphIds;
    return this;
  }

  public LensGraphResponse putSeedGraphIdsItem(String key, List<String> seedGraphIdsItem) {
    if (this.seedGraphIds == null) {
      this.seedGraphIds = new HashMap<>();
    }
    this.seedGraphIds.put(key, seedGraphIdsItem);
    return this;
  }

  /**
   * Get seedGraphIds
   * @return seedGraphIds
   */
  @javax.annotation.Nullable
  public Map<String, List<String>> getSeedGraphIds() {
    return seedGraphIds;
  }

  public void setSeedGraphIds(@javax.annotation.Nullable Map<String, List<String>> seedGraphIds) {
    this.seedGraphIds = seedGraphIds;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LensGraphResponse lensGraphResponse = (LensGraphResponse) o;
    return Objects.equals(this.graph, lensGraphResponse.graph) &&
        Objects.equals(this.seedGraphIds, lensGraphResponse.seedGraphIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(graph, seedGraphIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LensGraphResponse {\n");
    sb.append("    graph: ").append(toIndentedString(graph)).append("\n");
    sb.append("    seedGraphIds: ").append(toIndentedString(seedGraphIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("graph", "seed_graph_ids"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to LensGraphResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!LensGraphResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in LensGraphResponse is not found in the empty JSON string", LensGraphResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!LensGraphResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `LensGraphResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("graph") != null && !jsonObj.get("graph").isJsonNull() && !jsonObj.get("graph").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `graph` to be an array in the JSON string but got `%s`", jsonObj.get("graph").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LensGraphResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LensGraphResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LensGraphResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LensGraphResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<LensGraphResponse>() {
           @Override
           public void write(JsonWriter out, LensGraphResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LensGraphResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of LensGraphResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of LensGraphResponse
   * @throws IOException if the JSON string is invalid with respect to LensGraphResponse
   */
  public static LensGraphResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LensGraphResponse.class);
  }

  /**
   * Convert an instance of LensGraphResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

