/*
 * Fideo API
 * Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@fideo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.fideo.model;

import java.util.Objects;
import ai.fideo.model.LocationReq;
import ai.fideo.model.PersonNameReq;
import ai.fideo.model.SocialProfileReq;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.fideo.client.JSON;

/**
 * MultiFieldReq
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class MultiFieldReq {
  public static final String SERIALIZED_NAME_TWITTER = "twitter";
  @SerializedName(SERIALIZED_NAME_TWITTER)
  @javax.annotation.Nullable
  private String twitter;

  public static final String SERIALIZED_NAME_LINKEDIN = "linkedin";
  @SerializedName(SERIALIZED_NAME_LINKEDIN)
  @javax.annotation.Nullable
  private String linkedin;

  public static final String SERIALIZED_NAME_RECORD_ID = "recordId";
  @SerializedName(SERIALIZED_NAME_RECORD_ID)
  @javax.annotation.Nullable
  private String recordId;

  public static final String SERIALIZED_NAME_PERSON_ID = "personId";
  @SerializedName(SERIALIZED_NAME_PERSON_ID)
  @javax.annotation.Nullable
  private String personId;

  public static final String SERIALIZED_NAME_PARTNER_ID = "partnerId";
  @SerializedName(SERIALIZED_NAME_PARTNER_ID)
  @javax.annotation.Nullable
  private String partnerId;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  @javax.annotation.Nullable
  private LocationReq location;

  public static final String SERIALIZED_NAME_AVATAR = "avatar";
  @SerializedName(SERIALIZED_NAME_AVATAR)
  @javax.annotation.Nullable
  private String avatar;

  public static final String SERIALIZED_NAME_WEBSITE = "website";
  @SerializedName(SERIALIZED_NAME_WEBSITE)
  @javax.annotation.Nullable
  private String website;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nullable
  private String title;

  public static final String SERIALIZED_NAME_ORGANIZATION = "organization";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION)
  @javax.annotation.Nullable
  private String organization;

  public static final String SERIALIZED_NAME_EMAILS = "emails";
  @SerializedName(SERIALIZED_NAME_EMAILS)
  @javax.annotation.Nullable
  private List<String> emails = new ArrayList<>();

  public static final String SERIALIZED_NAME_PHONES = "phones";
  @SerializedName(SERIALIZED_NAME_PHONES)
  @javax.annotation.Nullable
  private List<String> phones = new ArrayList<>();

  public static final String SERIALIZED_NAME_SSN = "ssn";
  @SerializedName(SERIALIZED_NAME_SSN)
  @javax.annotation.Nullable
  private String ssn;

  public static final String SERIALIZED_NAME_SSNS = "ssns";
  @SerializedName(SERIALIZED_NAME_SSNS)
  @javax.annotation.Nullable
  private List<String> ssns = new ArrayList<>();

  public static final String SERIALIZED_NAME_PROFILES = "profiles";
  @SerializedName(SERIALIZED_NAME_PROFILES)
  @javax.annotation.Nullable
  private List<SocialProfileReq> profiles = new ArrayList<>();

  public static final String SERIALIZED_NAME_MAIDS = "maids";
  @SerializedName(SERIALIZED_NAME_MAIDS)
  @javax.annotation.Nullable
  private List<String> maids = new ArrayList<>();

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private PersonNameReq name;

  public static final String SERIALIZED_NAME_PARTNER_KEYS = "partnerKeys";
  @SerializedName(SERIALIZED_NAME_PARTNER_KEYS)
  @javax.annotation.Nullable
  private Map<String, String> partnerKeys = new HashMap<>();

  public static final String SERIALIZED_NAME_LI_NONID = "li_nonid";
  @SerializedName(SERIALIZED_NAME_LI_NONID)
  @javax.annotation.Nullable
  private String liNonid;

  public static final String SERIALIZED_NAME_PANORAMA_ID = "panoramaId";
  @SerializedName(SERIALIZED_NAME_PANORAMA_ID)
  @javax.annotation.Nullable
  private String panoramaId;

  public static final String SERIALIZED_NAME_GENERATE_PID = "generatePid";
  @SerializedName(SERIALIZED_NAME_GENERATE_PID)
  @javax.annotation.Nullable
  private Boolean generatePid;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nullable
  private String email;

  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  @javax.annotation.Nullable
  private String phone;

  public static final String SERIALIZED_NAME_PROFILE = "profile";
  @SerializedName(SERIALIZED_NAME_PROFILE)
  @javax.annotation.Nullable
  private SocialProfileReq profile;

  public static final String SERIALIZED_NAME_MAID = "maid";
  @SerializedName(SERIALIZED_NAME_MAID)
  @javax.annotation.Nullable
  private String maid;

  public MultiFieldReq() {
  }

  public MultiFieldReq twitter(@javax.annotation.Nullable String twitter) {
    this.twitter = twitter;
    return this;
  }

  /**
   * Get twitter
   * @return twitter
   */
  @javax.annotation.Nullable
  public String getTwitter() {
    return twitter;
  }

  public void setTwitter(@javax.annotation.Nullable String twitter) {
    this.twitter = twitter;
  }


  public MultiFieldReq linkedin(@javax.annotation.Nullable String linkedin) {
    this.linkedin = linkedin;
    return this;
  }

  /**
   * Get linkedin
   * @return linkedin
   */
  @javax.annotation.Nullable
  public String getLinkedin() {
    return linkedin;
  }

  public void setLinkedin(@javax.annotation.Nullable String linkedin) {
    this.linkedin = linkedin;
  }


  public MultiFieldReq recordId(@javax.annotation.Nullable String recordId) {
    this.recordId = recordId;
    return this;
  }

  /**
   * Get recordId
   * @return recordId
   */
  @javax.annotation.Nullable
  public String getRecordId() {
    return recordId;
  }

  public void setRecordId(@javax.annotation.Nullable String recordId) {
    this.recordId = recordId;
  }


  public MultiFieldReq personId(@javax.annotation.Nullable String personId) {
    this.personId = personId;
    return this;
  }

  /**
   * Get personId
   * @return personId
   */
  @javax.annotation.Nullable
  public String getPersonId() {
    return personId;
  }

  public void setPersonId(@javax.annotation.Nullable String personId) {
    this.personId = personId;
  }


  public MultiFieldReq partnerId(@javax.annotation.Nullable String partnerId) {
    this.partnerId = partnerId;
    return this;
  }

  /**
   * Get partnerId
   * @return partnerId
   */
  @javax.annotation.Nullable
  public String getPartnerId() {
    return partnerId;
  }

  public void setPartnerId(@javax.annotation.Nullable String partnerId) {
    this.partnerId = partnerId;
  }


  public MultiFieldReq location(@javax.annotation.Nullable LocationReq location) {
    this.location = location;
    return this;
  }

  /**
   * Get location
   * @return location
   */
  @javax.annotation.Nullable
  public LocationReq getLocation() {
    return location;
  }

  public void setLocation(@javax.annotation.Nullable LocationReq location) {
    this.location = location;
  }


  public MultiFieldReq avatar(@javax.annotation.Nullable String avatar) {
    this.avatar = avatar;
    return this;
  }

  /**
   * Get avatar
   * @return avatar
   */
  @javax.annotation.Nullable
  public String getAvatar() {
    return avatar;
  }

  public void setAvatar(@javax.annotation.Nullable String avatar) {
    this.avatar = avatar;
  }


  public MultiFieldReq website(@javax.annotation.Nullable String website) {
    this.website = website;
    return this;
  }

  /**
   * Get website
   * @return website
   */
  @javax.annotation.Nullable
  public String getWebsite() {
    return website;
  }

  public void setWebsite(@javax.annotation.Nullable String website) {
    this.website = website;
  }


  public MultiFieldReq title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }


  public MultiFieldReq organization(@javax.annotation.Nullable String organization) {
    this.organization = organization;
    return this;
  }

  /**
   * Get organization
   * @return organization
   */
  @javax.annotation.Nullable
  public String getOrganization() {
    return organization;
  }

  public void setOrganization(@javax.annotation.Nullable String organization) {
    this.organization = organization;
  }


  public MultiFieldReq emails(@javax.annotation.Nullable List<String> emails) {
    this.emails = emails;
    return this;
  }

  public MultiFieldReq addEmailsItem(String emailsItem) {
    if (this.emails == null) {
      this.emails = new ArrayList<>();
    }
    this.emails.add(emailsItem);
    return this;
  }

  /**
   * Get emails
   * @return emails
   */
  @javax.annotation.Nullable
  public List<String> getEmails() {
    return emails;
  }

  public void setEmails(@javax.annotation.Nullable List<String> emails) {
    this.emails = emails;
  }


  public MultiFieldReq phones(@javax.annotation.Nullable List<String> phones) {
    this.phones = phones;
    return this;
  }

  public MultiFieldReq addPhonesItem(String phonesItem) {
    if (this.phones == null) {
      this.phones = new ArrayList<>();
    }
    this.phones.add(phonesItem);
    return this;
  }

  /**
   * Get phones
   * @return phones
   */
  @javax.annotation.Nullable
  public List<String> getPhones() {
    return phones;
  }

  public void setPhones(@javax.annotation.Nullable List<String> phones) {
    this.phones = phones;
  }


  public MultiFieldReq ssn(@javax.annotation.Nullable String ssn) {
    this.ssn = ssn;
    return this;
  }

  /**
   * Singular shortcut for one SSN value. Internally equivalent to ssns with one item.
   * @return ssn
   */
  @javax.annotation.Nullable
  public String getSsn() {
    return ssn;
  }

  public void setSsn(@javax.annotation.Nullable String ssn) {
    this.ssn = ssn;
  }


  public MultiFieldReq ssns(@javax.annotation.Nullable List<String> ssns) {
    this.ssns = ssns;
    return this;
  }

  public MultiFieldReq addSsnsItem(String ssnsItem) {
    if (this.ssns == null) {
      this.ssns = new ArrayList<>();
    }
    this.ssns.add(ssnsItem);
    return this;
  }

  /**
   * Full SSN values as digits/dashes or SHA-256 hex digests. Verify accepts at most one.
   * @return ssns
   */
  @javax.annotation.Nullable
  public List<String> getSsns() {
    return ssns;
  }

  public void setSsns(@javax.annotation.Nullable List<String> ssns) {
    this.ssns = ssns;
  }


  public MultiFieldReq profiles(@javax.annotation.Nullable List<SocialProfileReq> profiles) {
    this.profiles = profiles;
    return this;
  }

  public MultiFieldReq addProfilesItem(SocialProfileReq profilesItem) {
    if (this.profiles == null) {
      this.profiles = new ArrayList<>();
    }
    this.profiles.add(profilesItem);
    return this;
  }

  /**
   * Get profiles
   * @return profiles
   */
  @javax.annotation.Nullable
  public List<SocialProfileReq> getProfiles() {
    return profiles;
  }

  public void setProfiles(@javax.annotation.Nullable List<SocialProfileReq> profiles) {
    this.profiles = profiles;
  }


  public MultiFieldReq maids(@javax.annotation.Nullable List<String> maids) {
    this.maids = maids;
    return this;
  }

  public MultiFieldReq addMaidsItem(String maidsItem) {
    if (this.maids == null) {
      this.maids = new ArrayList<>();
    }
    this.maids.add(maidsItem);
    return this;
  }

  /**
   * Get maids
   * @return maids
   */
  @javax.annotation.Nullable
  public List<String> getMaids() {
    return maids;
  }

  public void setMaids(@javax.annotation.Nullable List<String> maids) {
    this.maids = maids;
  }


  public MultiFieldReq name(@javax.annotation.Nullable PersonNameReq name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public PersonNameReq getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable PersonNameReq name) {
    this.name = name;
  }


  public MultiFieldReq partnerKeys(@javax.annotation.Nullable Map<String, String> partnerKeys) {
    this.partnerKeys = partnerKeys;
    return this;
  }

  public MultiFieldReq putPartnerKeysItem(String key, String partnerKeysItem) {
    if (this.partnerKeys == null) {
      this.partnerKeys = new HashMap<>();
    }
    this.partnerKeys.put(key, partnerKeysItem);
    return this;
  }

  /**
   * Get partnerKeys
   * @return partnerKeys
   */
  @javax.annotation.Nullable
  public Map<String, String> getPartnerKeys() {
    return partnerKeys;
  }

  public void setPartnerKeys(@javax.annotation.Nullable Map<String, String> partnerKeys) {
    this.partnerKeys = partnerKeys;
  }


  public MultiFieldReq liNonid(@javax.annotation.Nullable String liNonid) {
    this.liNonid = liNonid;
    return this;
  }

  /**
   * Get liNonid
   * @return liNonid
   */
  @javax.annotation.Nullable
  public String getLiNonid() {
    return liNonid;
  }

  public void setLiNonid(@javax.annotation.Nullable String liNonid) {
    this.liNonid = liNonid;
  }


  public MultiFieldReq panoramaId(@javax.annotation.Nullable String panoramaId) {
    this.panoramaId = panoramaId;
    return this;
  }

  /**
   * Get panoramaId
   * @return panoramaId
   */
  @javax.annotation.Nullable
  public String getPanoramaId() {
    return panoramaId;
  }

  public void setPanoramaId(@javax.annotation.Nullable String panoramaId) {
    this.panoramaId = panoramaId;
  }


  public MultiFieldReq generatePid(@javax.annotation.Nullable Boolean generatePid) {
    this.generatePid = generatePid;
    return this;
  }

  /**
   * Get generatePid
   * @return generatePid
   */
  @javax.annotation.Nullable
  public Boolean getGeneratePid() {
    return generatePid;
  }

  public void setGeneratePid(@javax.annotation.Nullable Boolean generatePid) {
    this.generatePid = generatePid;
  }


  public MultiFieldReq email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @javax.annotation.Nullable
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public MultiFieldReq phone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
    return this;
  }

  /**
   * Get phone
   * @return phone
   */
  @javax.annotation.Nullable
  public String getPhone() {
    return phone;
  }

  public void setPhone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
  }


  public MultiFieldReq profile(@javax.annotation.Nullable SocialProfileReq profile) {
    this.profile = profile;
    return this;
  }

  /**
   * Get profile
   * @return profile
   */
  @javax.annotation.Nullable
  public SocialProfileReq getProfile() {
    return profile;
  }

  public void setProfile(@javax.annotation.Nullable SocialProfileReq profile) {
    this.profile = profile;
  }


  public MultiFieldReq maid(@javax.annotation.Nullable String maid) {
    this.maid = maid;
    return this;
  }

  /**
   * Get maid
   * @return maid
   */
  @javax.annotation.Nullable
  public String getMaid() {
    return maid;
  }

  public void setMaid(@javax.annotation.Nullable String maid) {
    this.maid = maid;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultiFieldReq multiFieldReq = (MultiFieldReq) o;
    return Objects.equals(this.twitter, multiFieldReq.twitter) &&
        Objects.equals(this.linkedin, multiFieldReq.linkedin) &&
        Objects.equals(this.recordId, multiFieldReq.recordId) &&
        Objects.equals(this.personId, multiFieldReq.personId) &&
        Objects.equals(this.partnerId, multiFieldReq.partnerId) &&
        Objects.equals(this.location, multiFieldReq.location) &&
        Objects.equals(this.avatar, multiFieldReq.avatar) &&
        Objects.equals(this.website, multiFieldReq.website) &&
        Objects.equals(this.title, multiFieldReq.title) &&
        Objects.equals(this.organization, multiFieldReq.organization) &&
        Objects.equals(this.emails, multiFieldReq.emails) &&
        Objects.equals(this.phones, multiFieldReq.phones) &&
        Objects.equals(this.ssn, multiFieldReq.ssn) &&
        Objects.equals(this.ssns, multiFieldReq.ssns) &&
        Objects.equals(this.profiles, multiFieldReq.profiles) &&
        Objects.equals(this.maids, multiFieldReq.maids) &&
        Objects.equals(this.name, multiFieldReq.name) &&
        Objects.equals(this.partnerKeys, multiFieldReq.partnerKeys) &&
        Objects.equals(this.liNonid, multiFieldReq.liNonid) &&
        Objects.equals(this.panoramaId, multiFieldReq.panoramaId) &&
        Objects.equals(this.generatePid, multiFieldReq.generatePid) &&
        Objects.equals(this.email, multiFieldReq.email) &&
        Objects.equals(this.phone, multiFieldReq.phone) &&
        Objects.equals(this.profile, multiFieldReq.profile) &&
        Objects.equals(this.maid, multiFieldReq.maid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(twitter, linkedin, recordId, personId, partnerId, location, avatar, website, title, organization, emails, phones, ssn, ssns, profiles, maids, name, partnerKeys, liNonid, panoramaId, generatePid, email, phone, profile, maid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultiFieldReq {\n");
    sb.append("    twitter: ").append(toIndentedString(twitter)).append("\n");
    sb.append("    linkedin: ").append(toIndentedString(linkedin)).append("\n");
    sb.append("    recordId: ").append(toIndentedString(recordId)).append("\n");
    sb.append("    personId: ").append(toIndentedString(personId)).append("\n");
    sb.append("    partnerId: ").append(toIndentedString(partnerId)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    avatar: ").append(toIndentedString(avatar)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    emails: ").append(toIndentedString(emails)).append("\n");
    sb.append("    phones: ").append(toIndentedString(phones)).append("\n");
    sb.append("    ssn: ").append(toIndentedString(ssn)).append("\n");
    sb.append("    ssns: ").append(toIndentedString(ssns)).append("\n");
    sb.append("    profiles: ").append(toIndentedString(profiles)).append("\n");
    sb.append("    maids: ").append(toIndentedString(maids)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    partnerKeys: ").append(toIndentedString(partnerKeys)).append("\n");
    sb.append("    liNonid: ").append(toIndentedString(liNonid)).append("\n");
    sb.append("    panoramaId: ").append(toIndentedString(panoramaId)).append("\n");
    sb.append("    generatePid: ").append(toIndentedString(generatePid)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    maid: ").append(toIndentedString(maid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("twitter", "linkedin", "recordId", "personId", "partnerId", "location", "avatar", "website", "title", "organization", "emails", "phones", "ssn", "ssns", "profiles", "maids", "name", "partnerKeys", "li_nonid", "panoramaId", "generatePid", "email", "phone", "profile", "maid"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MultiFieldReq
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MultiFieldReq.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in MultiFieldReq is not found in the empty JSON string", MultiFieldReq.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("twitter") != null && !jsonObj.get("twitter").isJsonNull()) && !jsonObj.get("twitter").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `twitter` to be a primitive type in the JSON string but got `%s`", jsonObj.get("twitter").toString()));
      }
      if ((jsonObj.get("linkedin") != null && !jsonObj.get("linkedin").isJsonNull()) && !jsonObj.get("linkedin").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `linkedin` to be a primitive type in the JSON string but got `%s`", jsonObj.get("linkedin").toString()));
      }
      if ((jsonObj.get("recordId") != null && !jsonObj.get("recordId").isJsonNull()) && !jsonObj.get("recordId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `recordId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("recordId").toString()));
      }
      if ((jsonObj.get("personId") != null && !jsonObj.get("personId").isJsonNull()) && !jsonObj.get("personId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `personId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("personId").toString()));
      }
      if ((jsonObj.get("partnerId") != null && !jsonObj.get("partnerId").isJsonNull()) && !jsonObj.get("partnerId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `partnerId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("partnerId").toString()));
      }
      // validate the optional field `location`
      if (jsonObj.get("location") != null && !jsonObj.get("location").isJsonNull()) {
        LocationReq.validateJsonElement(jsonObj.get("location"));
      }
      if ((jsonObj.get("avatar") != null && !jsonObj.get("avatar").isJsonNull()) && !jsonObj.get("avatar").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `avatar` to be a primitive type in the JSON string but got `%s`", jsonObj.get("avatar").toString()));
      }
      if ((jsonObj.get("website") != null && !jsonObj.get("website").isJsonNull()) && !jsonObj.get("website").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `website` to be a primitive type in the JSON string but got `%s`", jsonObj.get("website").toString()));
      }
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if ((jsonObj.get("organization") != null && !jsonObj.get("organization").isJsonNull()) && !jsonObj.get("organization").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `organization` to be a primitive type in the JSON string but got `%s`", jsonObj.get("organization").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("emails") != null && !jsonObj.get("emails").isJsonNull() && !jsonObj.get("emails").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `emails` to be an array in the JSON string but got `%s`", jsonObj.get("emails").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("phones") != null && !jsonObj.get("phones").isJsonNull() && !jsonObj.get("phones").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `phones` to be an array in the JSON string but got `%s`", jsonObj.get("phones").toString()));
      }
      if ((jsonObj.get("ssn") != null && !jsonObj.get("ssn").isJsonNull()) && !jsonObj.get("ssn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ssn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ssn").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("ssns") != null && !jsonObj.get("ssns").isJsonNull() && !jsonObj.get("ssns").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ssns` to be an array in the JSON string but got `%s`", jsonObj.get("ssns").toString()));
      }
      if (jsonObj.get("profiles") != null && !jsonObj.get("profiles").isJsonNull()) {
        JsonArray jsonArrayprofiles = jsonObj.getAsJsonArray("profiles");
        if (jsonArrayprofiles != null) {
          // ensure the json data is an array
          if (!jsonObj.get("profiles").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `profiles` to be an array in the JSON string but got `%s`", jsonObj.get("profiles").toString()));
          }

          // validate the optional field `profiles` (array)
          for (int i = 0; i < jsonArrayprofiles.size(); i++) {
            SocialProfileReq.validateJsonElement(jsonArrayprofiles.get(i));
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("maids") != null && !jsonObj.get("maids").isJsonNull() && !jsonObj.get("maids").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `maids` to be an array in the JSON string but got `%s`", jsonObj.get("maids").toString()));
      }
      // validate the optional field `name`
      if (jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) {
        PersonNameReq.validateJsonElement(jsonObj.get("name"));
      }
      if ((jsonObj.get("li_nonid") != null && !jsonObj.get("li_nonid").isJsonNull()) && !jsonObj.get("li_nonid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `li_nonid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("li_nonid").toString()));
      }
      if ((jsonObj.get("panoramaId") != null && !jsonObj.get("panoramaId").isJsonNull()) && !jsonObj.get("panoramaId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `panoramaId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("panoramaId").toString()));
      }
      if ((jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if ((jsonObj.get("phone") != null && !jsonObj.get("phone").isJsonNull()) && !jsonObj.get("phone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `phone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("phone").toString()));
      }
      // validate the optional field `profile`
      if (jsonObj.get("profile") != null && !jsonObj.get("profile").isJsonNull()) {
        SocialProfileReq.validateJsonElement(jsonObj.get("profile"));
      }
      if ((jsonObj.get("maid") != null && !jsonObj.get("maid").isJsonNull()) && !jsonObj.get("maid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `maid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("maid").toString()));
      }
  }


  /**
   * Create an instance of MultiFieldReq given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MultiFieldReq
   * @throws IOException if the JSON string is invalid with respect to MultiFieldReq
   */
  public static MultiFieldReq fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MultiFieldReq.class);
  }

  /**
   * Convert an instance of MultiFieldReq to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

