/*
 * Fideo Production API
 * Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@fideo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.fideo.model;

import java.util.Objects;
import ai.fideo.model.SignalPatternResponseUnit;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.fideo.client.JSON;

/**
 * SignalPatternRecencyResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class SignalPatternRecencyResponse {
  public static final String SERIALIZED_NAME_HOUR = "hour";
  @SerializedName(SERIALIZED_NAME_HOUR)
  @javax.annotation.Nullable
  private SignalPatternResponseUnit hour;

  public static final String SERIALIZED_NAME_DAY = "day";
  @SerializedName(SERIALIZED_NAME_DAY)
  @javax.annotation.Nullable
  private SignalPatternResponseUnit day;

  public static final String SERIALIZED_NAME_WEEK = "week";
  @SerializedName(SERIALIZED_NAME_WEEK)
  @javax.annotation.Nullable
  private SignalPatternResponseUnit week;

  public static final String SERIALIZED_NAME_MONTH = "month";
  @SerializedName(SERIALIZED_NAME_MONTH)
  @javax.annotation.Nullable
  private SignalPatternResponseUnit month;

  public static final String SERIALIZED_NAME_SIX_MONTH = "sixMonth";
  @SerializedName(SERIALIZED_NAME_SIX_MONTH)
  @javax.annotation.Nullable
  private SignalPatternResponseUnit sixMonth;

  public static final String SERIALIZED_NAME_YEAR = "year";
  @SerializedName(SERIALIZED_NAME_YEAR)
  @javax.annotation.Nullable
  private SignalPatternResponseUnit year;

  public SignalPatternRecencyResponse() {
  }

  public SignalPatternRecencyResponse hour(@javax.annotation.Nullable SignalPatternResponseUnit hour) {
    this.hour = hour;
    return this;
  }

  /**
   * Get hour
   * @return hour
   */
  @javax.annotation.Nullable
  public SignalPatternResponseUnit getHour() {
    return hour;
  }

  public void setHour(@javax.annotation.Nullable SignalPatternResponseUnit hour) {
    this.hour = hour;
  }


  public SignalPatternRecencyResponse day(@javax.annotation.Nullable SignalPatternResponseUnit day) {
    this.day = day;
    return this;
  }

  /**
   * Get day
   * @return day
   */
  @javax.annotation.Nullable
  public SignalPatternResponseUnit getDay() {
    return day;
  }

  public void setDay(@javax.annotation.Nullable SignalPatternResponseUnit day) {
    this.day = day;
  }


  public SignalPatternRecencyResponse week(@javax.annotation.Nullable SignalPatternResponseUnit week) {
    this.week = week;
    return this;
  }

  /**
   * Get week
   * @return week
   */
  @javax.annotation.Nullable
  public SignalPatternResponseUnit getWeek() {
    return week;
  }

  public void setWeek(@javax.annotation.Nullable SignalPatternResponseUnit week) {
    this.week = week;
  }


  public SignalPatternRecencyResponse month(@javax.annotation.Nullable SignalPatternResponseUnit month) {
    this.month = month;
    return this;
  }

  /**
   * Get month
   * @return month
   */
  @javax.annotation.Nullable
  public SignalPatternResponseUnit getMonth() {
    return month;
  }

  public void setMonth(@javax.annotation.Nullable SignalPatternResponseUnit month) {
    this.month = month;
  }


  public SignalPatternRecencyResponse sixMonth(@javax.annotation.Nullable SignalPatternResponseUnit sixMonth) {
    this.sixMonth = sixMonth;
    return this;
  }

  /**
   * Get sixMonth
   * @return sixMonth
   */
  @javax.annotation.Nullable
  public SignalPatternResponseUnit getSixMonth() {
    return sixMonth;
  }

  public void setSixMonth(@javax.annotation.Nullable SignalPatternResponseUnit sixMonth) {
    this.sixMonth = sixMonth;
  }


  public SignalPatternRecencyResponse year(@javax.annotation.Nullable SignalPatternResponseUnit year) {
    this.year = year;
    return this;
  }

  /**
   * Get year
   * @return year
   */
  @javax.annotation.Nullable
  public SignalPatternResponseUnit getYear() {
    return year;
  }

  public void setYear(@javax.annotation.Nullable SignalPatternResponseUnit year) {
    this.year = year;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignalPatternRecencyResponse signalPatternRecencyResponse = (SignalPatternRecencyResponse) o;
    return Objects.equals(this.hour, signalPatternRecencyResponse.hour) &&
        Objects.equals(this.day, signalPatternRecencyResponse.day) &&
        Objects.equals(this.week, signalPatternRecencyResponse.week) &&
        Objects.equals(this.month, signalPatternRecencyResponse.month) &&
        Objects.equals(this.sixMonth, signalPatternRecencyResponse.sixMonth) &&
        Objects.equals(this.year, signalPatternRecencyResponse.year);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hour, day, week, month, sixMonth, year);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignalPatternRecencyResponse {\n");
    sb.append("    hour: ").append(toIndentedString(hour)).append("\n");
    sb.append("    day: ").append(toIndentedString(day)).append("\n");
    sb.append("    week: ").append(toIndentedString(week)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    sixMonth: ").append(toIndentedString(sixMonth)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("hour");
    openapiFields.add("day");
    openapiFields.add("week");
    openapiFields.add("month");
    openapiFields.add("sixMonth");
    openapiFields.add("year");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SignalPatternRecencyResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SignalPatternRecencyResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SignalPatternRecencyResponse is not found in the empty JSON string", SignalPatternRecencyResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SignalPatternRecencyResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SignalPatternRecencyResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `hour`
      if (jsonObj.get("hour") != null && !jsonObj.get("hour").isJsonNull()) {
        SignalPatternResponseUnit.validateJsonElement(jsonObj.get("hour"));
      }
      // validate the optional field `day`
      if (jsonObj.get("day") != null && !jsonObj.get("day").isJsonNull()) {
        SignalPatternResponseUnit.validateJsonElement(jsonObj.get("day"));
      }
      // validate the optional field `week`
      if (jsonObj.get("week") != null && !jsonObj.get("week").isJsonNull()) {
        SignalPatternResponseUnit.validateJsonElement(jsonObj.get("week"));
      }
      // validate the optional field `month`
      if (jsonObj.get("month") != null && !jsonObj.get("month").isJsonNull()) {
        SignalPatternResponseUnit.validateJsonElement(jsonObj.get("month"));
      }
      // validate the optional field `sixMonth`
      if (jsonObj.get("sixMonth") != null && !jsonObj.get("sixMonth").isJsonNull()) {
        SignalPatternResponseUnit.validateJsonElement(jsonObj.get("sixMonth"));
      }
      // validate the optional field `year`
      if (jsonObj.get("year") != null && !jsonObj.get("year").isJsonNull()) {
        SignalPatternResponseUnit.validateJsonElement(jsonObj.get("year"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SignalPatternRecencyResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SignalPatternRecencyResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SignalPatternRecencyResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SignalPatternRecencyResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<SignalPatternRecencyResponse>() {
           @Override
           public void write(JsonWriter out, SignalPatternRecencyResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SignalPatternRecencyResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SignalPatternRecencyResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SignalPatternRecencyResponse
   * @throws IOException if the JSON string is invalid with respect to SignalPatternRecencyResponse
   */
  public static SignalPatternRecencyResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SignalPatternRecencyResponse.class);
  }

  /**
   * Convert an instance of SignalPatternRecencyResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

