/*
 * Fideo API
 * This is a representation of the Fideo API based on the OpenAPI 3.0 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). Some useful links: - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@fideo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.fideo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Economic
 */
public class EconomicTest {
    private final Economic model = new Economic();

    /**
     * Model tests for Economic
     */
    @Test
    public void testEconomic() {
        // TODO: test Economic
    }

    /**
     * Test the property 'dwellingType'
     */
    @Test
    public void dwellingTypeTest() {
        // TODO: test dwellingType
    }

    /**
     * Test the property 'homeOwnership'
     */
    @Test
    public void homeOwnershipTest() {
        // TODO: test homeOwnership
    }

    /**
     * Test the property 'maritalStatus'
     */
    @Test
    public void maritalStatusTest() {
        // TODO: test maritalStatus
    }

    /**
     * Test the property 'presenceOfChildren'
     */
    @Test
    public void presenceOfChildrenTest() {
        // TODO: test presenceOfChildren
    }

    /**
     * Test the property 'income'
     */
    @Test
    public void incomeTest() {
        // TODO: test income
    }

    /**
     * Test the property 'netWorth'
     */
    @Test
    public void netWorthTest() {
        // TODO: test netWorth
    }

}
