/*
 * Fideo API
 * Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@fideo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.fideo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IpAddress
 */
public class IpAddressTest {
    private final IpAddress model = new IpAddress();

    /**
     * Model tests for IpAddress
     */
    @Test
    public void testIpAddress() {
        // TODO: test IpAddress
    }

    /**
     * Test the property 'firstSeenMs'
     */
    @Test
    public void firstSeenMsTest() {
        // TODO: test firstSeenMs
    }

    /**
     * Test the property 'lastSeenMs'
     */
    @Test
    public void lastSeenMsTest() {
        // TODO: test lastSeenMs
    }

    /**
     * Test the property 'observations'
     */
    @Test
    public void observationsTest() {
        // TODO: test observations
    }

    /**
     * Test the property 'confidence'
     */
    @Test
    public void confidenceTest() {
        // TODO: test confidence
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
