/*
 * Fideo API
 * This is a representation of the Fideo API based on the OpenAPI 3.0 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). Some useful links: - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@fideo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.fideo.model;

import ai.fideo.model.Evidence;
import ai.fideo.model.ScoreDetails;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MatchResponse
 */
public class MatchResponseTest {
    private final MatchResponse model = new MatchResponse();

    /**
     * Model tests for MatchResponse
     */
    @Test
    public void testMatchResponse() {
        // TODO: test MatchResponse
    }

    /**
     * Test the property 'addressLine1'
     */
    @Test
    public void addressLine1Test() {
        // TODO: test addressLine1
    }

    /**
     * Test the property 'addressLine2'
     */
    @Test
    public void addressLine2Test() {
        // TODO: test addressLine2
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'regionCode'
     */
    @Test
    public void regionCodeTest() {
        // TODO: test regionCode
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'continent'
     */
    @Test
    public void continentTest() {
        // TODO: test continent
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'familyName'
     */
    @Test
    public void familyNameTest() {
        // TODO: test familyName
    }

    /**
     * Test the property 'givenName'
     */
    @Test
    public void givenNameTest() {
        // TODO: test givenName
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'maid'
     */
    @Test
    public void maidTest() {
        // TODO: test maid
    }

    /**
     * Test the property 'social'
     */
    @Test
    public void socialTest() {
        // TODO: test social
    }

    /**
     * Test the property 'nonId'
     */
    @Test
    public void nonIdTest() {
        // TODO: test nonId
    }

    /**
     * Test the property 'panoramaId'
     */
    @Test
    public void panoramaIdTest() {
        // TODO: test panoramaId
    }

    /**
     * Test the property 'ipAddress'
     */
    @Test
    public void ipAddressTest() {
        // TODO: test ipAddress
    }

    /**
     * Test the property 'birthday'
     */
    @Test
    public void birthdayTest() {
        // TODO: test birthday
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'organization'
     */
    @Test
    public void organizationTest() {
        // TODO: test organization
    }

    /**
     * Test the property 'risk'
     */
    @Test
    public void riskTest() {
        // TODO: test risk
    }

    /**
     * Test the property 'evidence'
     */
    @Test
    public void evidenceTest() {
        // TODO: test evidence
    }

    /**
     * Test the property 'riskV2'
     */
    @Test
    public void riskV2Test() {
        // TODO: test riskV2
    }

    /**
     * Test the property 'riskV3'
     */
    @Test
    public void riskV3Test() {
        // TODO: test riskV3
    }

    /**
     * Test the property 'scoreDetails'
     */
    @Test
    public void scoreDetailsTest() {
        // TODO: test scoreDetails
    }

}
