/*
 * Fideo API
 * Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@fideo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.fideo.model;

import ai.fideo.model.Alias;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NameWithAlias
 */
public class NameWithAliasTest {
    private final NameWithAlias model = new NameWithAlias();

    /**
     * Model tests for NameWithAlias
     */
    @Test
    public void testNameWithAlias() {
        // TODO: test NameWithAlias
    }

    /**
     * Test the property 'first'
     */
    @Test
    public void firstTest() {
        // TODO: test first
    }

    /**
     * Test the property 'last'
     */
    @Test
    public void lastTest() {
        // TODO: test last
    }

    /**
     * Test the property 'middle'
     */
    @Test
    public void middleTest() {
        // TODO: test middle
    }

    /**
     * Test the property 'givenName'
     */
    @Test
    public void givenNameTest() {
        // TODO: test givenName
    }

    /**
     * Test the property 'familyName'
     */
    @Test
    public void familyNameTest() {
        // TODO: test familyName
    }

    /**
     * Test the property 'aliases'
     */
    @Test
    public void aliasesTest() {
        // TODO: test aliases
    }

}
