/*
 * Fideo API
 * Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@fideo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.fideo.model;

import ai.fideo.model.Demographics;
import ai.fideo.model.Economic;
import ai.fideo.model.Education;
import ai.fideo.model.Email;
import ai.fideo.model.Employment;
import ai.fideo.model.IpAddress;
import ai.fideo.model.Location;
import ai.fideo.model.NameWithAlias;
import ai.fideo.model.Phone;
import ai.fideo.model.Photo;
import ai.fideo.model.SignalsResponseV0;
import ai.fideo.model.SignalsResponseV20240424;
import ai.fideo.model.SocialProfileDetails;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V3VerifySignalsPost200Response
 */
public class V3VerifySignalsPost200ResponseTest {
    private final V3VerifySignalsPost200Response model = new V3VerifySignalsPost200Response();

    /**
     * Model tests for V3VerifySignalsPost200Response
     */
    @Test
    public void testV3VerifySignalsPost200Response() {
        // TODO: test V3VerifySignalsPost200Response
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'demographics'
     */
    @Test
    public void demographicsTest() {
        // TODO: test demographics
    }

    /**
     * Test the property 'locations'
     */
    @Test
    public void locationsTest() {
        // TODO: test locations
    }

    /**
     * Test the property 'emails'
     */
    @Test
    public void emailsTest() {
        // TODO: test emails
    }

    /**
     * Test the property 'phones'
     */
    @Test
    public void phonesTest() {
        // TODO: test phones
    }

    /**
     * Test the property 'personIds'
     */
    @Test
    public void personIdsTest() {
        // TODO: test personIds
    }

    /**
     * Test the property 'ipAddresses'
     */
    @Test
    public void ipAddressesTest() {
        // TODO: test ipAddresses
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'socialProfiles'
     */
    @Test
    public void socialProfilesTest() {
        // TODO: test socialProfiles
    }

    /**
     * Test the property 'employment'
     */
    @Test
    public void employmentTest() {
        // TODO: test employment
    }

    /**
     * Test the property 'education'
     */
    @Test
    public void educationTest() {
        // TODO: test education
    }

    /**
     * Test the property 'photos'
     */
    @Test
    public void photosTest() {
        // TODO: test photos
    }

    /**
     * Test the property 'economic'
     */
    @Test
    public void economicTest() {
        // TODO: test economic
    }

}
